"""
缓存键和 TTL 配置

定义所有缓存键的前缀和过期时间
"""

# ==================== 缓存键前缀 ====================

# 用户相关
USER_CACHE_PREFIX = "user"
USER_SESSION_PREFIX = "session"

# 内容相关
ITEM_CACHE_PREFIX = "item"
ITEM_LIST_PREFIX = "item:list"

# 标签相关
TAG_CACHE_PREFIX = "tag"

# 收藏相关
COLLECTION_CACHE_PREFIX = "collection"

# 外部 API 相关
TMDB_PREFIX = "tmdb"
DOUBAN_PREFIX = "douban"
GOOGLE_BOOKS_PREFIX = "google_books"
ANILIST_PREFIX = "anilist"


# ==================== TTL (Time-To-Live) 配置 ====================

# 短期缓存 (5 分钟)
SHORT_CACHE_TTL = 5 * 60

# 中期缓存 (30 分钟)
MEDIUM_CACHE_TTL = 30 * 60

# 长期缓存 (1 小时)
LONG_CACHE_TTL = 60 * 60

# 超长期缓存 (24 小时)
VERY_LONG_CACHE_TTL = 24 * 60 * 60

# 用户数据缓存
USER_CACHE_TTL = MEDIUM_CACHE_TTL
USER_SESSION_TTL = 7 * 24 * 60 * 60  # 7 天

# 内容数据缓存
ITEM_CACHE_TTL = LONG_CACHE_TTL
ITEM_LIST_TTL = MEDIUM_CACHE_TTL

# 标签缓存
TAG_CACHE_TTL = VERY_LONG_CACHE_TTL

# 收藏缓存
COLLECTION_CACHE_TTL = MEDIUM_CACHE_TTL

# 外部 API 缓存
TMDB_SEARCH_TTL = MEDIUM_CACHE_TTL  # 搜索结果 30 分钟
TMDB_MOVIE_DETAIL_TTL = VERY_LONG_CACHE_TTL  # 电影详情 24 小时
TMDB_TV_DETAIL_TTL = VERY_LONG_CACHE_TTL  # 剧集详情 24 小时

DOUBAN_SEARCH_TTL = MEDIUM_CACHE_TTL
DOUBAN_DETAIL_TTL = VERY_LONG_CACHE_TTL

GOOGLE_BOOKS_SEARCH_TTL = MEDIUM_CACHE_TTL
GOOGLE_BOOKS_DETAIL_TTL = VERY_LONG_CACHE_TTL

ANILIST_SEARCH_TTL = MEDIUM_CACHE_TTL
ANILIST_DETAIL_TTL = VERY_LONG_CACHE_TTL
