"""add enable_strict_search_filter to user_settings

Revision ID: 7fa2d15a6805
Revises: add_anon_home_access
Create Date: 2025-11-24 16:10:31.096729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fa2d15a6805'
down_revision = 'add_anon_home_access'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_key_configs', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='配置ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('api_key_configs', 'service',
               existing_type=postgresql.ENUM('TMDB', 'GOOGLE_BOOKS', 'BANGUMI', name='apikeyservice'),
               comment='API 服务类型',
               existing_comment='API服务类型',
               existing_nullable=False)
    op.alter_column('api_key_configs', 'api_key',
               existing_type=sa.VARCHAR(length=500),
               comment='API 密钥（加密存储）',
               existing_comment='API密钥',
               existing_nullable=True)
    op.alter_column('api_key_configs', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment='API 基础 URL',
               existing_comment='API基础URL',
               existing_nullable=True)
    op.alter_column('background_tasks', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='任务ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('background_tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment='任务进度（0-100）',
               existing_comment='任务进度',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('background_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('background_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_messages', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='消息ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('conversation_messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='对话ID',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='角色',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'message_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='消息元数据',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('conversation_messages_conversation_id_fkey', 'conversation_messages', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_messages', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='对话ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('conversations_id_seq'::regclass)"))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='会话标题',
               existing_nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('conversations_user_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.alter_column('item_tags', 'id',
               existing_type=sa.INTEGER(),
               comment='关系ID(已废弃)',
               existing_comment='关系ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('items', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='数据源(tmdb/google_books/bangumi)',
               existing_comment='数据源',
               existing_nullable=False)
    op.alter_column('items', 'content_type',
               existing_type=sa.VARCHAR(length=50),
               comment='内容类型(movie/tv/anime/book/game)',
               existing_comment='内容类型',
               existing_nullable=False)
    op.alter_column('items', 'type',
               existing_type=postgresql.ENUM('MOVIE', 'TV_SERIES', 'ANIME', 'BOOK', name='itemtype'),
               comment='条目类型(枚举)',
               existing_comment='条目类型',
               existing_nullable=True)
    op.alter_column('items', 'cover_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='封面图URL(兼容旧版)',
               existing_comment='封面图URL',
               existing_nullable=True)
    op.alter_column('items', 'cast',
               existing_type=sa.TEXT(),
               comment='演员列表(JSON格式)',
               existing_comment='演员列表',
               existing_nullable=True)
    op.alter_column('items', 'genres',
               existing_type=sa.TEXT(),
               comment='类型列表(JSON格式)',
               existing_comment='类型列表',
               existing_nullable=True)
    op.alter_column('items', 'duration',
               existing_type=sa.INTEGER(),
               comment='时长(分钟)或页数',
               existing_comment='时长或页数',
               existing_nullable=True)
    op.alter_column('items', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='额外元数据(JSON格式)',
               existing_comment='额外元数据',
               existing_nullable=True)
    op.alter_column('items', 'external_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='外部平台ID映射(JSON)',
               existing_comment='外部平台ID映射',
               existing_nullable=True)
    op.alter_column('items', 'external_ratings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='外部平台评分(JSON)',
               existing_comment='外部平台评分',
               existing_nullable=True)
    op.alter_column('llm_configs', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='配置ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('llm_configs', 'provider',
               existing_type=postgresql.ENUM('siliconflow', 'deepseek', 'openai', 'claude', name='llmprovider'),
               comment='LLM 提供商',
               existing_comment='LLM提供商',
               existing_nullable=False,
               existing_server_default=sa.text("'siliconflow'::llmprovider"))
    op.alter_column('llm_configs', 'api_key',
               existing_type=sa.VARCHAR(length=500),
               comment='API 密钥（加密存储）',
               existing_comment='API密钥',
               existing_nullable=True)
    op.alter_column('llm_configs', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment='API 基础 URL',
               existing_comment='API基础URL',
               existing_nullable=True)
    op.alter_column('llm_configs', 'default_model',
               existing_type=sa.VARCHAR(length=200),
               comment='默认使用的模型',
               existing_comment='默认模型',
               existing_nullable=True)
    op.alter_column('llm_configs', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_comment='温度参数')
    op.alter_column('llm_configs', 'max_tokens',
               existing_type=sa.INTEGER(),
               comment='最大生成 token 数',
               existing_comment='最大token数',
               existing_nullable=True)
    op.alter_column('llm_configs', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               comment='nucleus sampling 参数',
               existing_comment='top_p参数',
               existing_server_default=sa.text("'1'::double precision"))
    op.drop_index('ix_llm_configs_provider', table_name='llm_configs')
    op.drop_column('llm_configs', 'is_default')
    op.drop_column('llm_configs', 'extra_config')
    op.alter_column('summaries', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='总结ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('summaries', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('summaries', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='总结标题',
               existing_nullable=False)
    op.alter_column('summaries', 'period_type',
               existing_type=postgresql.ENUM('WEEK', 'MONTH', 'YEAR', 'CUSTOM', name='periodtype'),
               comment=None,
               existing_comment='时期类型',
               existing_nullable=False,
               existing_server_default=sa.text("'MONTH'::periodtype"))
    op.alter_column('summaries', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='开始日期',
               existing_nullable=False)
    op.alter_column('summaries', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='结束日期',
               existing_nullable=False)
    op.alter_column('summaries', 'summary_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='总结文本',
               existing_nullable=False)
    op.alter_column('summaries', 'keywords',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='关键词列表',
               existing_nullable=True)
    op.alter_column('summaries', 'statistics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='统计数据快照',
               existing_nullable=True)
    op.alter_column('summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_settings', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='设置ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('system_settings', 'enable_explore',
               existing_type=sa.BOOLEAN(),
               comment='启用探索/推荐功能',
               existing_comment='启用探索功能',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('system_settings', 'allow_user_ai_tag_settings',
               existing_type=sa.BOOLEAN(),
               comment='允许用户自行设置 AI 自动标签',
               existing_comment='允许用户设置AI标签',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tags', 'is_auto',
               existing_type=sa.BOOLEAN(),
               comment='是否AI自动生成',
               existing_comment='是否自动生成',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tags', 'color',
               existing_type=sa.VARCHAR(length=20),
               comment='标签颜色(十六进制)',
               existing_comment='标签颜色',
               existing_nullable=True)
    op.alter_column('user_item_tags', 'id',
               existing_type=sa.INTEGER(),
               comment='关系ID',
               existing_comment='关联ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_items', 'rating',
               existing_type=sa.INTEGER(),
               comment='个人评分(0-10)',
               existing_comment='个人评分',
               existing_nullable=True)
    op.alter_column('user_items', 'watched_date',
               existing_type=sa.DATE(),
               comment='观看完成日期(兼容旧版)',
               existing_comment='观看完成日期',
               existing_nullable=True)
    op.alter_column('user_items', 'progress',
               existing_type=sa.INTEGER(),
               comment='观看进度(集数/页数)',
               existing_comment='观看进度',
               existing_nullable=True)
    op.alter_column('user_items', 'is_favorite',
               existing_type=sa.INTEGER(),
               comment='是否收藏(0/1)',
               existing_comment='是否收藏',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('user_settings', sa.Column('enable_strict_search_filter', sa.Boolean(), server_default='true', nullable=False, comment='启用严格搜索过滤（只返回标题包含关键词的结果）'))
    op.alter_column('user_settings', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='设置ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_settings', 'auto_generate_tags',
               existing_type=sa.BOOLEAN(),
               comment='创建记录时自动生成标签',
               existing_comment='自动生成标签',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('uq_user_settings_user_id', 'user_settings', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='邮箱地址',
               existing_comment='邮箱',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='加密后的密码',
               existing_comment='密码哈希',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               comment='真实姓名',
               existing_comment='全名',
               existing_nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='是否已验证邮箱',
               existing_comment='是否验证',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='是否验证',
               existing_comment='是否已验证邮箱',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               comment='全名',
               existing_comment='真实姓名',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='密码哈希',
               existing_comment='加密后的密码',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='邮箱',
               existing_comment='邮箱地址',
               existing_nullable=False)
    op.create_unique_constraint('uq_user_settings_user_id', 'user_settings', ['user_id'])
    op.alter_column('user_settings', 'auto_generate_tags',
               existing_type=sa.BOOLEAN(),
               comment='自动生成标签',
               existing_comment='创建记录时自动生成标签',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_settings', 'id',
               existing_type=sa.INTEGER(),
               comment='设置ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user_settings', 'enable_strict_search_filter')
    op.alter_column('user_items', 'is_favorite',
               existing_type=sa.INTEGER(),
               comment='是否收藏',
               existing_comment='是否收藏(0/1)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_items', 'progress',
               existing_type=sa.INTEGER(),
               comment='观看进度',
               existing_comment='观看进度(集数/页数)',
               existing_nullable=True)
    op.alter_column('user_items', 'watched_date',
               existing_type=sa.DATE(),
               comment='观看完成日期',
               existing_comment='观看完成日期(兼容旧版)',
               existing_nullable=True)
    op.alter_column('user_items', 'rating',
               existing_type=sa.INTEGER(),
               comment='个人评分',
               existing_comment='个人评分(0-10)',
               existing_nullable=True)
    op.alter_column('user_item_tags', 'id',
               existing_type=sa.INTEGER(),
               comment='关联ID',
               existing_comment='关系ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tags', 'color',
               existing_type=sa.VARCHAR(length=20),
               comment='标签颜色',
               existing_comment='标签颜色(十六进制)',
               existing_nullable=True)
    op.alter_column('tags', 'is_auto',
               existing_type=sa.BOOLEAN(),
               comment='是否自动生成',
               existing_comment='是否AI自动生成',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('system_settings', 'allow_user_ai_tag_settings',
               existing_type=sa.BOOLEAN(),
               comment='允许用户设置AI标签',
               existing_comment='允许用户自行设置 AI 自动标签',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('system_settings', 'enable_explore',
               existing_type=sa.BOOLEAN(),
               comment='启用探索功能',
               existing_comment='启用探索/推荐功能',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('system_settings', 'id',
               existing_type=sa.INTEGER(),
               comment='设置ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('summaries', 'statistics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='统计数据快照',
               existing_nullable=True)
    op.alter_column('summaries', 'keywords',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='关键词列表',
               existing_nullable=True)
    op.alter_column('summaries', 'summary_text',
               existing_type=sa.TEXT(),
               comment='总结文本',
               existing_nullable=False)
    op.alter_column('summaries', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='结束日期',
               existing_nullable=False)
    op.alter_column('summaries', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='开始日期',
               existing_nullable=False)
    op.alter_column('summaries', 'period_type',
               existing_type=postgresql.ENUM('WEEK', 'MONTH', 'YEAR', 'CUSTOM', name='periodtype'),
               comment='时期类型',
               existing_nullable=False,
               existing_server_default=sa.text("'MONTH'::periodtype"))
    op.alter_column('summaries', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='总结标题',
               existing_nullable=False)
    op.alter_column('summaries', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('summaries', 'id',
               existing_type=sa.INTEGER(),
               comment='总结ID',
               existing_nullable=False,
               autoincrement=True)
    op.add_column('llm_configs', sa.Column('extra_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='额外配置'))
    op.add_column('llm_configs', sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='是否默认'))
    op.create_index('ix_llm_configs_provider', 'llm_configs', ['provider'], unique=False)
    op.alter_column('llm_configs', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               comment='top_p参数',
               existing_comment='nucleus sampling 参数',
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('llm_configs', 'max_tokens',
               existing_type=sa.INTEGER(),
               comment='最大token数',
               existing_comment='最大生成 token 数',
               existing_nullable=True)
    op.alter_column('llm_configs', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='温度参数')
    op.alter_column('llm_configs', 'default_model',
               existing_type=sa.VARCHAR(length=200),
               comment='默认模型',
               existing_comment='默认使用的模型',
               existing_nullable=True)
    op.alter_column('llm_configs', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment='API基础URL',
               existing_comment='API 基础 URL',
               existing_nullable=True)
    op.alter_column('llm_configs', 'api_key',
               existing_type=sa.VARCHAR(length=500),
               comment='API密钥',
               existing_comment='API 密钥（加密存储）',
               existing_nullable=True)
    op.alter_column('llm_configs', 'provider',
               existing_type=postgresql.ENUM('siliconflow', 'deepseek', 'openai', 'claude', name='llmprovider'),
               comment='LLM提供商',
               existing_comment='LLM 提供商',
               existing_nullable=False,
               existing_server_default=sa.text("'siliconflow'::llmprovider"))
    op.alter_column('llm_configs', 'id',
               existing_type=sa.INTEGER(),
               comment='配置ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('items', 'external_ratings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='外部平台评分',
               existing_comment='外部平台评分(JSON)',
               existing_nullable=True)
    op.alter_column('items', 'external_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='外部平台ID映射',
               existing_comment='外部平台ID映射(JSON)',
               existing_nullable=True)
    op.alter_column('items', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='额外元数据',
               existing_comment='额外元数据(JSON格式)',
               existing_nullable=True)
    op.alter_column('items', 'duration',
               existing_type=sa.INTEGER(),
               comment='时长或页数',
               existing_comment='时长(分钟)或页数',
               existing_nullable=True)
    op.alter_column('items', 'genres',
               existing_type=sa.TEXT(),
               comment='类型列表',
               existing_comment='类型列表(JSON格式)',
               existing_nullable=True)
    op.alter_column('items', 'cast',
               existing_type=sa.TEXT(),
               comment='演员列表',
               existing_comment='演员列表(JSON格式)',
               existing_nullable=True)
    op.alter_column('items', 'cover_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='封面图URL',
               existing_comment='封面图URL(兼容旧版)',
               existing_nullable=True)
    op.alter_column('items', 'type',
               existing_type=postgresql.ENUM('MOVIE', 'TV_SERIES', 'ANIME', 'BOOK', name='itemtype'),
               comment='条目类型',
               existing_comment='条目类型(枚举)',
               existing_nullable=True)
    op.alter_column('items', 'content_type',
               existing_type=sa.VARCHAR(length=50),
               comment='内容类型',
               existing_comment='内容类型(movie/tv/anime/book/game)',
               existing_nullable=False)
    op.alter_column('items', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='数据源',
               existing_comment='数据源(tmdb/google_books/bangumi)',
               existing_nullable=False)
    op.alter_column('item_tags', 'id',
               existing_type=sa.INTEGER(),
               comment='关系ID',
               existing_comment='关系ID(已废弃)',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_user_id_fkey', 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='会话标题',
               existing_nullable=True)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.INTEGER(),
               comment='对话ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('conversations_id_seq'::regclass)"))
    op.drop_constraint(None, 'conversation_messages', type_='foreignkey')
    op.create_foreign_key('conversation_messages_conversation_id_fkey', 'conversation_messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_messages', 'message_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='消息元数据',
               existing_nullable=True)
    op.alter_column('conversation_messages', 'content',
               existing_type=sa.TEXT(),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='角色',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               comment='对话ID',
               existing_nullable=False)
    op.alter_column('conversation_messages', 'id',
               existing_type=sa.INTEGER(),
               comment='消息ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('background_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='更新时间',
               existing_server_default=sa.text('now()'))
    op.alter_column('background_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('background_tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment='任务进度',
               existing_comment='任务进度（0-100）',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('background_tasks', 'id',
               existing_type=sa.INTEGER(),
               comment='任务ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('api_key_configs', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment='API基础URL',
               existing_comment='API 基础 URL',
               existing_nullable=True)
    op.alter_column('api_key_configs', 'api_key',
               existing_type=sa.VARCHAR(length=500),
               comment='API密钥',
               existing_comment='API 密钥（加密存储）',
               existing_nullable=True)
    op.alter_column('api_key_configs', 'service',
               existing_type=postgresql.ENUM('TMDB', 'GOOGLE_BOOKS', 'BANGUMI', name='apikeyservice'),
               comment='API服务类型',
               existing_comment='API 服务类型',
               existing_nullable=False)
    op.alter_column('api_key_configs', 'id',
               existing_type=sa.INTEGER(),
               comment='配置ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


