"""add_user_item_tags_and_update_tags

Revision ID: aa1ef49d8a36
Revises: 8d3e0e4f1f07
Create Date: 2025-11-03 02:56:02.964372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1ef49d8a36'
down_revision = '8d3e0e4f1f07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_item_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_item_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_item_id'], ['user_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_item_id', 'tag_id', name='uix_user_item_tag')
    )
    op.create_index(op.f('ix_user_item_tags_id'), 'user_item_tags', ['id'], unique=False)
    op.create_index(op.f('ix_user_item_tags_tag_id'), 'user_item_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_user_item_tags_user_item_id'), 'user_item_tags', ['user_item_id'], unique=False)
    op.add_column('tags', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_tags_name', table_name='tags')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_unique_constraint('uix_user_tag_name', 'tags', ['user_id', 'name'])
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint('uix_user_tag_name', 'tags', type_='unique')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.create_index('ix_tags_name', 'tags', ['name'], unique=True)
    op.drop_column('tags', 'user_id')
    op.drop_index(op.f('ix_user_item_tags_user_item_id'), table_name='user_item_tags')
    op.drop_index(op.f('ix_user_item_tags_tag_id'), table_name='user_item_tags')
    op.drop_index(op.f('ix_user_item_tags_id'), table_name='user_item_tags')
    op.drop_table('user_item_tags')
    # ### end Alembic commands ###


