"""update_user_item_fields

Revision ID: 8d3e0e4f1f07
Revises: 77aff2c8e975
Create Date: 2025-10-31 03:46:52.745335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d3e0e4f1f07'
down_revision = '77aff2c8e975'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_items', sa.Column('started_at', sa.String(length=50), nullable=True))
    op.add_column('user_items', sa.Column('completed_at', sa.String(length=50), nullable=True))
    op.alter_column('user_items', 'status',
               existing_type=postgresql.ENUM('WANT', 'DOING', 'DONE', name='itemstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user_items', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_items', 'rating',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('user_items', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('WANT', 'DOING', 'DONE', name='itemstatus'),
               existing_nullable=False)
    op.drop_column('user_items', 'completed_at')
    op.drop_column('user_items', 'started_at')
    # ### end Alembic commands ###


