"""add_llm_config_table

Revision ID: fa5f55d0067b
Revises: aa1ef49d8a36
Create Date: 2025-11-04 02:35:30.312765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa5f55d0067b'
down_revision = 'aa1ef49d8a36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建 Enum 类型
    llmprovider_enum = postgresql.ENUM('SILICONFLOW', 'DEEPSEEK', 'OPENAI', 'CLAUDE', name='llmprovider')
    llmprovider_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('llm_configs', sa.Column('default_model', sa.String(length=200), nullable=True, comment='默认使用的模型'))
    op.add_column('llm_configs', sa.Column('enabled', sa.Boolean(), nullable=False, server_default='true', comment='是否启用'))
    op.add_column('llm_configs', sa.Column('auto_tag_enabled', sa.Boolean(), nullable=False, server_default='false', comment='是否启用自动标签'))
    op.add_column('llm_configs', sa.Column('description', sa.Text(), nullable=True, comment='配置描述'))
    
    # 先将 provider 列改为允许 NULL
    op.alter_column('llm_configs', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    
    # 然后修改类型
    op.execute("ALTER TABLE llm_configs ALTER COLUMN provider TYPE llmprovider USING provider::text::llmprovider")
    
    # 添加注释
    op.execute("COMMENT ON COLUMN llm_configs.provider IS 'LLM 提供商'")
    op.alter_column('llm_configs', 'api_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=True,
               comment='API 密钥（加密存储）')
    op.alter_column('llm_configs', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment='API 基础 URL',
               existing_nullable=True)
    op.alter_column('llm_configs', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='温度参数',
               existing_nullable=False)
    op.alter_column('llm_configs', 'max_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='最大生成 token 数')
    op.alter_column('llm_configs', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='nucleus sampling 参数',
               existing_nullable=False)
    op.drop_index('ix_llm_configs_provider', table_name='llm_configs')
    op.drop_column('llm_configs', 'extra_config')
    op.drop_column('llm_configs', 'model_name')
    op.drop_column('llm_configs', 'is_active')
    op.drop_column('llm_configs', 'is_default')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('llm_configs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('llm_configs', sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('llm_configs', sa.Column('extra_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix_llm_configs_provider', 'llm_configs', ['provider'], unique=True)
    op.alter_column('llm_configs', 'top_p',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='nucleus sampling 参数',
               existing_nullable=False)
    op.alter_column('llm_configs', 'max_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='最大生成 token 数')
    op.alter_column('llm_configs', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='温度参数',
               existing_nullable=False)
    op.alter_column('llm_configs', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='API 基础 URL',
               existing_nullable=True)
    op.alter_column('llm_configs', 'api_key',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=False,
               comment=None,
               existing_comment='API 密钥（加密存储）')
    
    # 修改 provider 列类型回 VARCHAR
    op.execute("ALTER TABLE llm_configs ALTER COLUMN provider TYPE VARCHAR(50) USING provider::text")
    
    op.drop_column('llm_configs', 'description')
    op.drop_column('llm_configs', 'auto_tag_enabled')
    op.drop_column('llm_configs', 'enabled')
    op.drop_column('llm_configs', 'default_model')
    
    # 删除 Enum 类型
    postgresql.ENUM('SILICONFLOW', 'DEEPSEEK', 'OPENAI', 'CLAUDE', name='llmprovider').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


