"""add_api_key_configs_table

Revision ID: d002e93ff086
Revises: a1b2c3d4e5f6
Create Date: 2025-11-08 12:27:00.084179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd002e93ff086'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service', sa.Enum('TMDB', 'GOOGLE_BOOKS', 'BANGUMI', name='apikeyservice'), nullable=False, comment='API 服务类型'),
    sa.Column('api_key', sa.String(length=500), nullable=True, comment='API 密钥（加密存储）'),
    sa.Column('base_url', sa.String(length=500), nullable=True, comment='API 基础 URL'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True, comment='最后测试时间'),
    sa.Column('test_status', sa.Enum('NOT_TESTED', 'SUCCESS', 'FAILED', name='teststatus'), nullable=False, comment='测试状态'),
    sa.Column('test_message', sa.Text(), nullable=True, comment='测试消息'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service')
    )
    op.create_index(op.f('ix_api_key_configs_id'), 'api_key_configs', ['id'], unique=False)
    
    # 插入初始配置数据
    from datetime import datetime
    op.execute(f"""
        INSERT INTO api_key_configs (service, api_key, base_url, enabled, test_status, description, created_at, updated_at)
        VALUES 
        ('TMDB', NULL, 'https://api.themoviedb.org/3', true, 'NOT_TESTED', '电影和电视剧数据库', '{datetime.utcnow()}', '{datetime.utcnow()}'),
        ('GOOGLE_BOOKS', NULL, 'https://www.googleapis.com/books/v1', true, 'NOT_TESTED', 'Google 图书数据库', '{datetime.utcnow()}', '{datetime.utcnow()}'),
        ('BANGUMI', NULL, 'https://api.bgm.tv', true, 'NOT_TESTED', 'Bangumi 动漫数据库', '{datetime.utcnow()}', '{datetime.utcnow()}')
    """)
    
    op.drop_index('ix_background_jobs_id', table_name='background_jobs')
    op.drop_index('ix_background_jobs_job_type', table_name='background_jobs')
    op.drop_index('ix_background_jobs_status', table_name='background_jobs')
    op.drop_index('ix_background_jobs_user_id', table_name='background_jobs')
    op.drop_table('background_jobs')
    op.alter_column('background_tasks', 'task_id',
               existing_type=sa.VARCHAR(length=50),
               comment='任务唯一标识',
               existing_nullable=False)
    op.alter_column('background_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               comment='任务类型',
               existing_nullable=False)
    op.alter_column('background_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='任务状态',
               existing_nullable=False)
    op.alter_column('background_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('background_tasks', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='任务参数',
               existing_nullable=True)
    op.alter_column('background_tasks', 'result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='任务结果',
               existing_nullable=True)
    op.alter_column('background_tasks', 'error_message',
               existing_type=sa.TEXT(),
               comment='错误信息',
               existing_nullable=True)
    op.alter_column('background_tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment='任务进度（0-100）',
               existing_nullable=True)
    op.alter_column('background_tasks', 'progress_message',
               existing_type=sa.VARCHAR(length=200),
               comment='进度消息',
               existing_nullable=True)
    op.alter_column('background_tasks', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='开始处理时间',
               existing_nullable=True)
    op.alter_column('background_tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='完成时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('background_tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('background_tasks', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='开始处理时间',
               existing_nullable=True)
    op.alter_column('background_tasks', 'progress_message',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='进度消息',
               existing_nullable=True)
    op.alter_column('background_tasks', 'progress',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='任务进度（0-100）',
               existing_nullable=True)
    op.alter_column('background_tasks', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='错误信息',
               existing_nullable=True)
    op.alter_column('background_tasks', 'result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='任务结果',
               existing_nullable=True)
    op.alter_column('background_tasks', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='任务参数',
               existing_nullable=True)
    op.alter_column('background_tasks', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属用户ID',
               existing_nullable=False)
    op.alter_column('background_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='任务状态',
               existing_nullable=False)
    op.alter_column('background_tasks', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='任务类型',
               existing_nullable=False)
    op.alter_column('background_tasks', 'task_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='任务唯一标识',
               existing_nullable=False)
    op.create_table('background_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_type', postgresql.ENUM('SUMMARY_GENERATION', 'AI_CHAT', name='jobtype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), autoincrement=False, nullable=False),
    sa.Column('progress', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False, comment='进度百分比 0-100'),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='任务参数'),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='任务结果（JSON格式）'),
    sa.Column('result_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='结果对象ID（如summary_id）'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='错误信息'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='background_jobs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='background_jobs_pkey')
    )
    op.create_index('ix_background_jobs_user_id', 'background_jobs', ['user_id'], unique=False)
    op.create_index('ix_background_jobs_status', 'background_jobs', ['status'], unique=False)
    op.create_index('ix_background_jobs_job_type', 'background_jobs', ['job_type'], unique=False)
    op.create_index('ix_background_jobs_id', 'background_jobs', ['id'], unique=False)
    op.drop_index(op.f('ix_api_key_configs_id'), table_name='api_key_configs')
    op.drop_table('api_key_configs')
    # ### end Alembic commands ###


