"""add_default_library_status_to_user_settings

Revision ID: f37843123bef
Revises: e1ac83b46865
Create Date: 2025-12-01 10:53:25.493993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37843123bef'
down_revision = 'e1ac83b46865'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('default_library_status', sa.String(length=50), server_default='want_to_watch', nullable=False, comment='我的记录页面默认筛选状态'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'default_library_status')
    # ### end Alembic commands ###


