"""add_chinese_comments_to_all_tables

Revision ID: 1180bba91402
Revises: ae7caf68cf4b
Create Date: 2025-11-04 04:54:25.619909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1180bba91402'
down_revision = 'ae7caf68cf4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection_items', 'id',
               existing_type=sa.INTEGER(),
               comment='关系ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('collection_items', 'collection_id',
               existing_type=sa.INTEGER(),
               comment='收藏集ID',
               existing_nullable=False)
    op.alter_column('collection_items', 'user_item_id',
               existing_type=sa.INTEGER(),
               comment='用户记录ID',
               existing_nullable=False)
    op.alter_column('collection_items', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='在收藏集中的排序',
               existing_nullable=False)
    op.alter_column('collection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('collection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('collections', 'id',
               existing_type=sa.INTEGER(),
               comment='收藏集ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('collections', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('collections', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment='收藏集名称',
               existing_nullable=False)
    op.alter_column('collections', 'description',
               existing_type=sa.TEXT(),
               comment='收藏集描述',
               existing_nullable=True)
    op.alter_column('collections', 'cover_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='封面图URL',
               existing_nullable=True)
    op.alter_column('collections', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment='是否公开',
               existing_nullable=False)
    op.alter_column('collections', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='排序顺序',
               existing_nullable=False)
    op.alter_column('collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('collections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('item_tags', 'id',
               existing_type=sa.INTEGER(),
               comment='关系ID(已废弃)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('item_tags', 'item_id',
               existing_type=sa.INTEGER(),
               comment='条目ID',
               existing_nullable=False)
    op.alter_column('item_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               comment='标签ID',
               existing_nullable=False)
    op.alter_column('item_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('item_tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('items', 'id',
               existing_type=sa.INTEGER(),
               comment='条目ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('items', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               comment='外部数据源ID',
               existing_nullable=False)
    op.alter_column('items', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='数据源(tmdb/google_books/bangumi)',
               existing_nullable=False)
    op.alter_column('items', 'content_type',
               existing_type=sa.VARCHAR(length=50),
               comment='内容类型(movie/tv/anime/book/game)',
               existing_nullable=False)
    op.alter_column('items', 'type',
               existing_type=postgresql.ENUM('MOVIE', 'TV_SERIES', 'ANIME', 'BOOK', name='itemtype'),
               comment='条目类型(枚举)',
               existing_nullable=True)
    op.alter_column('items', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment='标题',
               existing_nullable=False)
    op.alter_column('items', 'original_title',
               existing_type=sa.VARCHAR(length=500),
               comment='原始标题',
               existing_nullable=True)
    op.alter_column('items', 'description',
               existing_type=sa.TEXT(),
               comment='简介描述',
               existing_nullable=True)
    op.alter_column('items', 'poster_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='海报图URL',
               existing_nullable=True)
    op.alter_column('items', 'backdrop_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='背景图URL',
               existing_nullable=True)
    op.alter_column('items', 'cover_url',
               existing_type=sa.VARCHAR(length=1000),
               comment='封面图URL(兼容旧版)',
               existing_nullable=True)
    op.alter_column('items', 'release_date',
               existing_type=sa.VARCHAR(length=50),
               comment='发布日期',
               existing_nullable=True)
    op.alter_column('items', 'release_year',
               existing_type=sa.INTEGER(),
               comment='发行年份',
               existing_nullable=True)
    op.alter_column('items', 'year',
               existing_type=sa.VARCHAR(length=10),
               comment='年份字符串',
               existing_nullable=True)
    op.alter_column('items', 'director',
               existing_type=sa.VARCHAR(length=255),
               comment='导演',
               existing_nullable=True)
    op.alter_column('items', 'author',
               existing_type=sa.VARCHAR(length=255),
               comment='作者',
               existing_nullable=True)
    op.alter_column('items', 'cast',
               existing_type=sa.TEXT(),
               comment='演员列表(JSON格式)',
               existing_nullable=True)
    op.alter_column('items', 'genres',
               existing_type=sa.TEXT(),
               comment='类型列表(JSON格式)',
               existing_nullable=True)
    op.alter_column('items', 'duration',
               existing_type=sa.INTEGER(),
               comment='时长(分钟)或页数',
               existing_nullable=True)
    op.alter_column('items', 'language',
               existing_type=sa.VARCHAR(length=50),
               comment='语言',
               existing_nullable=True)
    op.alter_column('items', 'country',
               existing_type=sa.VARCHAR(length=100),
               comment='国家/地区',
               existing_nullable=True)
    op.alter_column('items', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='额外元数据(JSON格式)',
               existing_nullable=True)
    op.alter_column('items', 'external_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='外部平台ID映射(JSON)',
               existing_nullable=True)
    op.alter_column('items', 'external_ratings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='外部平台评分(JSON)',
               existing_nullable=True)
    op.alter_column('items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('llm_configs', 'provider',
               existing_type=postgresql.ENUM('SILICONFLOW', 'DEEPSEEK', 'OPENAI', 'CLAUDE', name='llmprovider'),
               nullable=False,
               existing_comment='LLM 提供商')
    op.alter_column('llm_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('llm_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('tags', 'id',
               existing_type=sa.INTEGER(),
               comment='标签ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('tags_id_seq'::regclass)"))
    op.alter_column('tags', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='标签名称',
               existing_nullable=False)
    op.alter_column('tags', 'type',
               existing_type=postgresql.ENUM('EMOTION', 'THEME', 'STYLE', 'CUSTOM', name='tagtype'),
               comment='标签类型',
               existing_nullable=False)
    op.alter_column('tags', 'is_auto',
               existing_type=sa.BOOLEAN(),
               comment='是否AI自动生成',
               existing_nullable=False)
    op.alter_column('tags', 'color',
               existing_type=sa.VARCHAR(length=20),
               comment='标签颜色(十六进制)',
               existing_nullable=True)
    op.alter_column('tags', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment='标签描述',
               existing_nullable=True)
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('user_item_tags', 'id',
               existing_type=sa.INTEGER(),
               comment='关系ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_item_tags', 'user_item_id',
               existing_type=sa.INTEGER(),
               comment='用户记录ID',
               existing_nullable=False)
    op.alter_column('user_item_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               comment='标签ID',
               existing_nullable=False)
    op.alter_column('user_item_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('user_item_tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('user_items', 'id',
               existing_type=sa.INTEGER(),
               comment='记录ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_items_id_seq'::regclass)"))
    op.alter_column('user_items', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_items', 'item_id',
               existing_type=sa.INTEGER(),
               comment='条目ID',
               existing_nullable=False)
    op.alter_column('user_items', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='观看状态',
               existing_nullable=False)
    op.alter_column('user_items', 'rating',
               existing_type=sa.INTEGER(),
               comment='个人评分(0-10)',
               existing_nullable=True)
    op.alter_column('user_items', 'notes',
               existing_type=sa.TEXT(),
               comment='个人笔记',
               existing_nullable=True)
    op.alter_column('user_items', 'started_at',
               existing_type=sa.VARCHAR(length=50),
               comment='开始日期',
               existing_nullable=True)
    op.alter_column('user_items', 'completed_at',
               existing_type=sa.VARCHAR(length=50),
               comment='完成日期',
               existing_nullable=True)
    op.alter_column('user_items', 'watched_date',
               existing_type=sa.DATE(),
               comment='观看完成日期(兼容旧版)',
               existing_nullable=True)
    op.alter_column('user_items', 'progress',
               existing_type=sa.INTEGER(),
               comment='观看进度(集数/页数)',
               existing_nullable=True)
    op.alter_column('user_items', 'is_favorite',
               existing_type=sa.INTEGER(),
               comment='是否收藏(0/1)',
               existing_nullable=False)
    op.alter_column('user_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('user_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='邮箱地址',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='用户名',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='加密后的密码',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               comment='真实姓名',
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment='头像URL',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活',
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment='是否已验证邮箱',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'moderator', 'admin', 'super_admin', name='userrole'),
               comment='用户角色',
               existing_nullable=False,
               existing_server_default=sa.text("'user'::userrole"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'moderator', 'admin', 'super_admin', name='userrole'),
               comment=None,
               existing_comment='用户角色',
               existing_nullable=False,
               existing_server_default=sa.text("'user'::userrole"))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否已验证邮箱',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='头像URL',
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='真实姓名',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='加密后的密码',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='邮箱地址',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.alter_column('user_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('user_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('user_items', 'is_favorite',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='是否收藏(0/1)',
               existing_nullable=False)
    op.alter_column('user_items', 'progress',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='观看进度(集数/页数)',
               existing_nullable=True)
    op.alter_column('user_items', 'watched_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='观看完成日期(兼容旧版)',
               existing_nullable=True)
    op.alter_column('user_items', 'completed_at',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='完成日期',
               existing_nullable=True)
    op.alter_column('user_items', 'started_at',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='开始日期',
               existing_nullable=True)
    op.alter_column('user_items', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='个人笔记',
               existing_nullable=True)
    op.alter_column('user_items', 'rating',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='个人评分(0-10)',
               existing_nullable=True)
    op.alter_column('user_items', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='观看状态',
               existing_nullable=False)
    op.alter_column('user_items', 'item_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='条目ID',
               existing_nullable=False)
    op.alter_column('user_items', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_items', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='记录ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_items_id_seq'::regclass)"))
    op.alter_column('user_item_tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('user_item_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('user_item_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='标签ID',
               existing_nullable=False)
    op.alter_column('user_item_tags', 'user_item_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户记录ID',
               existing_nullable=False)
    op.alter_column('user_item_tags', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关系ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('tags', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='标签描述',
               existing_nullable=True)
    op.alter_column('tags', 'color',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='标签颜色(十六进制)',
               existing_nullable=True)
    op.alter_column('tags', 'is_auto',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否AI自动生成',
               existing_nullable=False)
    op.alter_column('tags', 'type',
               existing_type=postgresql.ENUM('EMOTION', 'THEME', 'STYLE', 'CUSTOM', name='tagtype'),
               comment=None,
               existing_comment='标签类型',
               existing_nullable=False)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='标签名称',
               existing_nullable=False)
    op.alter_column('tags', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('tags', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='标签ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('tags_id_seq'::regclass)"))
    op.alter_column('llm_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('llm_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('llm_configs', 'provider',
               existing_type=postgresql.ENUM('SILICONFLOW', 'DEEPSEEK', 'OPENAI', 'CLAUDE', name='llmprovider'),
               nullable=True,
               existing_comment='LLM 提供商')
    op.alter_column('items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('items', 'external_ratings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='外部平台评分(JSON)',
               existing_nullable=True)
    op.alter_column('items', 'external_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='外部平台ID映射(JSON)',
               existing_nullable=True)
    op.alter_column('items', 'extra_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='额外元数据(JSON格式)',
               existing_nullable=True)
    op.alter_column('items', 'country',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='国家/地区',
               existing_nullable=True)
    op.alter_column('items', 'language',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='语言',
               existing_nullable=True)
    op.alter_column('items', 'duration',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='时长(分钟)或页数',
               existing_nullable=True)
    op.alter_column('items', 'genres',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='类型列表(JSON格式)',
               existing_nullable=True)
    op.alter_column('items', 'cast',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='演员列表(JSON格式)',
               existing_nullable=True)
    op.alter_column('items', 'author',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='作者',
               existing_nullable=True)
    op.alter_column('items', 'director',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='导演',
               existing_nullable=True)
    op.alter_column('items', 'year',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='年份字符串',
               existing_nullable=True)
    op.alter_column('items', 'release_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='发行年份',
               existing_nullable=True)
    op.alter_column('items', 'release_date',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='发布日期',
               existing_nullable=True)
    op.alter_column('items', 'cover_url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='封面图URL(兼容旧版)',
               existing_nullable=True)
    op.alter_column('items', 'backdrop_url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='背景图URL',
               existing_nullable=True)
    op.alter_column('items', 'poster_url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='海报图URL',
               existing_nullable=True)
    op.alter_column('items', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='简介描述',
               existing_nullable=True)
    op.alter_column('items', 'original_title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='原始标题',
               existing_nullable=True)
    op.alter_column('items', 'title',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='标题',
               existing_nullable=False)
    op.alter_column('items', 'type',
               existing_type=postgresql.ENUM('MOVIE', 'TV_SERIES', 'ANIME', 'BOOK', name='itemtype'),
               comment=None,
               existing_comment='条目类型(枚举)',
               existing_nullable=True)
    op.alter_column('items', 'content_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='内容类型(movie/tv/anime/book/game)',
               existing_nullable=False)
    op.alter_column('items', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='数据源(tmdb/google_books/bangumi)',
               existing_nullable=False)
    op.alter_column('items', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='外部数据源ID',
               existing_nullable=False)
    op.alter_column('items', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='条目ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('item_tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('item_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('item_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='标签ID',
               existing_nullable=False)
    op.alter_column('item_tags', 'item_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='条目ID',
               existing_nullable=False)
    op.alter_column('item_tags', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关系ID(已废弃)',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('collections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('collections', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=False)
    op.alter_column('collections', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否公开',
               existing_nullable=False)
    op.alter_column('collections', 'cover_url',
               existing_type=sa.VARCHAR(length=1000),
               comment=None,
               existing_comment='封面图URL',
               existing_nullable=True)
    op.alter_column('collections', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='收藏集描述',
               existing_nullable=True)
    op.alter_column('collections', 'name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='收藏集名称',
               existing_nullable=False)
    op.alter_column('collections', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('collections', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='收藏集ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('collection_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('collection_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('collection_items', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='在收藏集中的排序',
               existing_nullable=False)
    op.alter_column('collection_items', 'user_item_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户记录ID',
               existing_nullable=False)
    op.alter_column('collection_items', 'collection_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='收藏集ID',
               existing_nullable=False)
    op.alter_column('collection_items', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='关系ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


