"""add_enable_stats_and_enable_ai_assistant_to_system_settings

Revision ID: 33e07af34248
Revises: 92383805e2db
Create Date: 2025-12-25 16:07:25.059144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e07af34248'
down_revision = '92383805e2db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('enable_stats', sa.Boolean(), server_default='true', nullable=False, comment='启用数据统计页面'))
    op.add_column('system_settings', sa.Column('enable_ai_assistant', sa.Boolean(), server_default='true', nullable=False, comment='启用AI助手页面'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'enable_ai_assistant')
    op.drop_column('system_settings', 'enable_stats')
    # ### end Alembic commands ###


