"""change_rating_to_float

Revision ID: f9e403884273
Revises: f37843123bef
Create Date: 2025-12-04 11:11:55.858836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e403884273'
down_revision = 'f37843123bef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_items', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_comment='个人评分(0-10)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_items', 'rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_comment='个人评分(0-10)',
               existing_nullable=True)
    # ### end Alembic commands ###


