"""add_allow_user_ai_tag_settings

Revision ID: 20251106_0300
Revises: 20251105_165140
Create Date: 2025-11-06 03:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251106_0300'
down_revision = '20251105_165140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', 
        sa.Column('allow_user_ai_tag_settings', sa.Boolean(), 
                  server_default='true', nullable=False, 
                  comment='允许用户自行设置 AI 自动标签')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'allow_user_ai_tag_settings')
    # ### end Alembic commands ###

