"""add_external_id_and_source_to_items

Revision ID: 77aff2c8e975
Revises: 2fbf5706c5dc
Create Date: 2025-10-31 03:44:31.771534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77aff2c8e975'
down_revision = '2fbf5706c5dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('external_id', sa.String(length=255), nullable=False))
    op.add_column('items', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('items', sa.Column('content_type', sa.String(length=50), nullable=False))
    op.add_column('items', sa.Column('poster_url', sa.String(length=1000), nullable=True))
    op.add_column('items', sa.Column('backdrop_url', sa.String(length=1000), nullable=True))
    op.add_column('items', sa.Column('release_date', sa.String(length=50), nullable=True))
    op.add_column('items', sa.Column('year', sa.String(length=10), nullable=True))
    op.add_column('items', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.alter_column('items', 'type',
               existing_type=postgresql.ENUM('MOVIE', 'TV_SERIES', 'ANIME', 'BOOK', name='itemtype'),
               nullable=True)
    op.create_index(op.f('ix_items_content_type'), 'items', ['content_type'], unique=False)
    op.create_index(op.f('ix_items_external_id'), 'items', ['external_id'], unique=False)
    op.create_index(op.f('ix_items_source'), 'items', ['source'], unique=False)
    op.create_unique_constraint('uix_external_id_source', 'items', ['external_id', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_external_id_source', 'items', type_='unique')
    op.drop_index(op.f('ix_items_source'), table_name='items')
    op.drop_index(op.f('ix_items_external_id'), table_name='items')
    op.drop_index(op.f('ix_items_content_type'), table_name='items')
    op.alter_column('items', 'type',
               existing_type=postgresql.ENUM('MOVIE', 'TV_SERIES', 'ANIME', 'BOOK', name='itemtype'),
               nullable=False)
    op.drop_column('items', 'extra_data')
    op.drop_column('items', 'year')
    op.drop_column('items', 'release_date')
    op.drop_column('items', 'backdrop_url')
    op.drop_column('items', 'poster_url')
    op.drop_column('items', 'content_type')
    op.drop_column('items', 'source')
    op.drop_column('items', 'external_id')
    # ### end Alembic commands ###


